version: "3.2"
services:
  cypress:
    build: ./automation/e2e
    environment:
      - DISPLAY=novnc:1.0
      - CYPRESS_BASE_URL=http://webring
    depends_on:
      - novnc
    entrypoint:
      - bash
      - -c
      - npx wait-on http://novnc && cypress open --project /project/automation/e2e
    working_dir: /project/automation/e2e
    volumes:
      - ./:/project:ro
      - ./automation/e2e:/project/automation/e2e
      - ./automation/site-fetcher/.fonts.conf:/root/.fonts.conf:ro
  novnc:
    image: dorowu/ubuntu-desktop-lxde-vnc
    environment:
      - RESOLUTION=1280x720
    ports:
      - "6080:80"
    volumes:
      - ./automation/e2e/xvfb.sh:/usr/local/bin/xvfb.sh
  webring:
    image: caddy:latest
    volumes:
      - ./:/usr/share/caddy:ro
    ports:
      - "6081:80"
