name: E2E
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Run development server and wait for server to be available.
      # See: https://www.npmjs.com/package/serve
      #      https://www.npmjs.com/package/wait-on
      - run: npx serve & npx wait-on http://localhost:5000

      # Install Cypress
      - run: cd automation/e2e && yarn

      # See: https://github.com/cypress-io/github-action
      - name: Cypress Run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          record: true
          # See: https://github.com/cypress-io/github-action#parallel
          parallel: true
          project: ./automation/e2e
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
