name: Review PR
on:
  workflow_dispatch:
    inputs:
      pr:
        description: 'PR number'     
        required: true
      url:
        description: 'Web URL'     
        required: true
jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn
      - run: node automation/pr-validator
        env:
          ENCRYPTION_SECRET: ${{ secrets.ENCRYPTION_SECRET }}
          SITE_FETCHER_API_KEY: ${{ secrets.SITE_FETCHER_API_KEY }}
          BOT_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
